###################################################
# GLobal Processing Flags
###################################################

global_processing_flags:
    EMPTY_ANNOTATION: blank
    QUESTION_DELIMITER: __
    QUESTION_PREFIX: question
    QUESTION_MAIN: species

###################################################
# Pre-Processing Flags
###################################################

pre_processing_flags:
    exif_data_timestamps:
     - DateTime
     - DateTimeOriginal
     - EXIF:DateTime
     - EXIF:DateTimeOriginal
    exif_tag_groups_to_extract:
     - EXIF
     - MakerNotes
     - Composite
    exif_tags_to_exclude:
     - EXIF:ThumbnailImage
     - MakerNotes:PreviewImage
    general:
     capture_delta_seconds: 5
    image_check_parameters:
     all_black:
       percent: 0.8
       thresh: 30
     all_white:
       percent: 0.8
       thresh: 200
     captures_with_too_many_images:
       max_images: 3
     time_lapse_days:
       max_days: 30
     time_too_new:
       max_year: 2018
     time_too_old:
       min_year: 2012
    image_checks:
     - all_black
     - all_white
     - corrupt_file
     - corrupt_exif
     - empty_exif
     - time_lapse
     - time_too_new
     - time_too_old
     - captures_with_too_many_images
    image_checks_invalidate:
     - all_black
     - all_white
     - corrupt_exif
     - empty_exif
    image_checks_delete:
     - corrupt_file
    image_checks_time:
     - time_lapse
     - time_too_new
     - time_too_old
     - captures_with_too_many_images
    time_formats:
      exif_input_datetime_format: '%Y:%m:%d %H:%M:%S'
      output_date_format: '%Y-%m-%d'
      output_datetime_format: '%Y-%m-%d %H:%M:%S'
      output_time_format: '%H:%M:%S'

###################################################
# Subject Extractor
###################################################
subject_extractor_flags:
    SUBJECT_ADD_LOCATION_DATA: true
    SUBJECT_DATA_TO_ADD:
     - retirement_reason
     - retired_at
     - created_at
    SUBJECT_METADATA_NAME_MAPPER:
     '#capture': capture
     '#roll': roll
     '#season': season
     '#site': site
    SUBJECT_METADATA_TO_ADD:
     - '#season'
     - '#roll'
     - '#site'
     - '#capture'

###################################################
# Flags to define the bheavior of adding
# Subject Info
###################################################

add_subject_info_flags:
    SUBJECT_DATA_TO_ADD:
     - retirement_reason
     - retired_at
     - created_at
    SUBJECT_INFO_MAPPER:
     '#capture': capture
     '#roll': roll
     '#season': season
     '#site': site
    SUBJECT_METADATA_TO_ADD:
     - season
     - roll
     - site
     - capture


###################################################
# Flags to define the bheavior of the
# Plurality Aggregator
###################################################

plurality_aggregation_flags:
    COUNTS_TO_ORDINAL_MAPPER:
      '': 0
      '11-50': 11
      '51+': 12
    QUESTION_COUNTS:
     - count
     - horns_count
    QUESTION_MAIN: species
    QUESTION_MAIN_EMPTY: blank



###################################################
# Flags to define the bheavior of the
# Legacy Extractor
###################################################

legacy_extractor_flags:
    ANSWER_TYPE_MAPPER:
      eating:
       false: 0
       true: 1
      interacting:
      eating:
       false: 0
       true: 1
      moving:
       false: 0
       true: 1
      resting:
       false: 0
       true: 1
      species:
        no animals present: blank
        nothing: blank
        '': blank
      standing:
       false: 0
       true: 1
      young_present:
       false: 0
       true: 1

    CLASSIFICATION_INFO_TO_ADD:
     - user_name
     - created_at
     - subject_id
     - capture_event_id
     - retirement_reason
     - season
     - site
     - roll
     - filenames
     - timestamps
     - classification_id
    CSV_HEADER_MAPPER:
     babies: young_present
     id: classification_id
     retire_reason: retirement_reason
     species_count: count
     subject_zooniverse_id: subject_id
    QUESTIONS:
     - species
     - count
     - standing
     - resting
     - moving
     - eating
     - interacting
     - young_present
    QUESTION_PREFIX: question
    QUESTION_DELIMITER: __



# Subject info to add from the legacy classifications export
add_subject_info_flags_legacy:
 - season
 - roll
 - site
 - capture
 - retirement_reason
 - retired_at
 - created_at
 - filenames
 - timestamps
 - capture_id


###################################################
# Flags to define the bheavior of the Extractor
###################################################

extractor_flags:
    ANSWER_MAPPER:
      0: '0'
      n: '0'
      'no': '0'
      1: '1'
      y: '1'
      'yes': '1'
    ANSWER_TYPE_MAPPER:
      species:
        no animals present: blank
        noanimalspresent: blank
        nothing: blank
        nothinghere: blank
        nothingthere: blank
      count:
        '1150': '11-50'
        '51': '51+'
      horns_count:
        '1150': '11-50'
        '51': '51+'
    CLASSIFICATION_INFO_MAPPER:
      subject_ids: subject_id
    CLASSIFICATION_INFO_TO_ADD:
     - user_name
     - user_id
     - created_at
     - subject_ids
     - workflow_id
     - workflow_version
     - classification_id
    QUESTIONS_TO_IGNORE:
     - dontcare
    QUESTION_NAME_MAPPER:
      arethereanyyoungpresent: young_present
      choice: species
      doyouseeanyantlers: antlers_visible
      doyouseeanyhorns: horns_visible
      howmany: count
      howmanyanimalscanyouseethathavehorns: horns_count
      question: species
    QUESTION_PREFIX: question
    QUESTION_DELIMITER: __
    RETIREMENT_INFO_TO_ADD:
     - retirement_reason
     - retired_at
